
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/Utilities.ipynb
import torch as T
import numpy as np

def set_seed(x):
    np.random.seed(x)
    T.manual_seed(x)
    T.backends.cudnn.deterministic = True
    T.backends.cudnn.benchmark  = False
    if T.cuda.is_available(): T.cuda.manual_seed_all(x)

def byte2np_RGB_img(response):
    img1d = np.fromstring(response.image_data_uint8, dtype=np.uint8)
    # reshape array to 4 channel image array H X W X 4
    img_rgb = img1d.reshape(response.height, response.width, 1)
    # original image is fliped vertica